### PR TITLE
Lumingxu dev

### PR DESCRIPTION
**Pull request by Abalagu**
Iteration 0 submission

### CODE REVIEW

**Comment by unkown512** [comment]
If you guys want to create a new directory for documentation just submit request here and upload docs inside it. I will merge once request is up

**Comment by Abalagu** [comment]
I apologize for the misclick.  We regarded the repo under unknown512 for production only.  We've forked a copy as course project repo, and uploaded the iteration 0 documents there.  If you're fine with us submitting here, we'll ask which way the TA prefers.

**Comment by unkown512** [comment]
That works for me, but it might be easier if you created some branches
under this repo and submit those to the TA.

I recently finalized some changes with the production server, so the
database_setup.py needs to be run after dropping the tables. I will be
uploading one more change later tonight.

If you look at the ‘request_data’ table, this is what y’all need for the
qualtrics api. Their is a column named ‘approved’ and once set to 1, the
system can get the corresponding data for that record (row).

The user profile data is stored in:
static/data/user_id
So I recommend storing the users data here from qualtrics in some directory.

Respectfully,
DJ

**Comment by unkown512** [comment]
You also have to configure a user admin account through the mysql command
line.

The admin is able to increase the access level of other users once created.

Run:
mysql -u <user> -p

Once logged in:
use aggiestemdl
update security set access_level=‘#’ where user_id=‘id’

**Pull request closed without merging**
